---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    lkey: lvalue
spec:
  ports:
    - port: 3306
  selector:
    lkey: lvalue
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    lkey: lvalue
    type: workload
    workload_app_name: MySQL
    workload_openebs_name: NFS
spec:
  selector:
    matchLabels:
      lkey: lvalue
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        lkey: lvalue
        tier: mysql
        type: workload
        workload_app_name: MySQL
        workload_openebs_name: NFS
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: testclaim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testclaim
  labels:
    lkey: lvalue
spec:
  storageClassName: testclass 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: volume-capacity
