---
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - test_vars.yml

  tasks:
    - block:

        ## Generating the testname for deployment
        - include_tasks: /e2e-tests/utils/fcm/create_testname.yml

        ## RECORD START-OF-TEST IN E2E RESULT CR
        - include_tasks: /e2e-tests/utils/fcm/update_e2e_result_resource.yml
          vars:
            status: 'SOT'

        - name: Replace the storage capacity placeholder
          replace:
             path: "{{ mysql_application_deployment }}"
             regexp: "volume-capacity"
             replace: "{{ mysql_capacity }}" 

        - name: Replace the storageclass placeholder with provider
          replace:
            path: "{{ mysql_application_deployment }}"
            regexp: "testclass"
            replace: "{{ mysql_storage_class }}" 

        - name: Replace the pvc placeholder with provider
          replace:
            path: "{{ mysql_application_deployment }}"
            regexp: "testclaim"
            replace: "{{ mysql_pvc_claim }}"
          
        - name: Replace the storageclass placeholder with provider
          replace:
            path: "{{ wordpress_application_deployment }}"
            regexp: "testclass"
            replace: "{{ wordpress_storage_class }}"            

        - name: Replace the storage capacity placeholder
          replace:
             path: "{{ wordpress_application_deployment }}"
             regexp: "volume-capacity"
             replace: "{{ wordpress_capacity }}" 

        - name: Replace the pvc placeholder with provider
          replace:
            path: "{{ wordpress_application_deployment }}"
            regexp: "testclaim"
            replace: "{{ wordpress_pvc_claim }}"

        - name: Replace the access mode for the pvc
          replace:
            path: "{{ wordpress_application_deployment }}"
            regexp: "accesstype"
            replace: "{{ access_mode }}"

        - block:

            - include_tasks: /e2e-tests/utils/k8s/pre_create_app_deploy.yml
              vars: 
                application_deployment: "{{ item }}"
              with_items:
                 - "{{ mysql_application_deployment }}"
                 - "{{ wordpress_application_deployment }}"

            - name: Create the mysql secrete pass
              shell: kubectl create secret generic mysql-pass --from-literal=password={{ mysql_pass }} -n {{ app_ns }}
              args:
                executable: /bin/bash
                          
             ## Deploying the mysql application
            - include_tasks: /e2e-tests/utils/k8s/deploy_single_app.yml
              vars:
                check_app_pod: 'no'
                delay: 10
                retries: 20
                application_deployment: "{{ item }}"
              with_items:
                 - "{{ mysql_application_deployment }}"
                 - "{{ wordpress_application_deployment }}"

          when: "'deprovision' not in action"

        - block:

            - name: Check if the application to be deleted is running.
              shell: kubectl get pods -n {{ app_ns }} -l {{ app_label }} --no-headers -o custom-columns=:status.phase
              args:
                executable: /bin/bash
              register: result
              until: "'Running' in result.stdout"
              delay: 5
              retries: 60

            - name: Delete the mysql application deployment.
              shell: kubectl delete -f {{ mysql_application_deployment }} -n {{ app_ns }}
              args:
                executable: /bin/bash

            - name: Delete the wordpress application deployment.
              shell: kubectl delete -f {{ wordpress_application_deployment }} -n {{ app_ns }}
              args:
                executable: /bin/bash

            - name: Check if the PVC is deleted.
              shell: kubectl get pvc -n {{ app_ns }} --no-headers
              args:
                executable: /bin/bash
              register: resource_list
              until: "mysql_pvc_claim not in resource_list.stdout"
              delay: 5
              retries: 120

            - name: Delete the namespace.
              shell: kubectl delete ns {{ app_ns }}
              args:
                executable: /bin/bash                

          when: "'deprovision' is in action"

        - set_fact:
            flag: "Pass"

      rescue:
        - name: Setting fail flag
          set_fact:
            flag: "Fail"

      always:
        ## RECORD END-OF-TEST IN E2E RESULT CR
        - include_tasks: /e2e-tests/utils/fcm/update_e2e_result_resource.yml
          vars:
            status: 'EOT'
