---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  generateName: svc-chaos-
spec:
  template:
    metadata:
      labels:
        app: svc-chaos
    spec:
      containers:
      - name: svc-chaos
        image: ubuntu:16.04
        command: ["/bin/bash"]
        args: ["-c", "sleep 100000"]
        resources:
          requests:
            cpu: 10m
            memory: 5M
          limits:
            cpu: 100m
            memory: 20M
        volumeMounts:
          - name: bus
            mountPath: /var/run
          - name: root
            mountPath: /node
        securityContext:
          privileged: true
        tty: true
      volumes:
        - name: bus
          hostPath:
            path: /var/run
        - name: root
          hostPath:
            path: /
            type: ""
