---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  labels:
    lkey: lvalue
spec:
  ports:
    - port: 9000
    #  nodePort: 32703
      protocol: TCP
  selector:
    app: minio
  sessionAffinity: None
  type: NodePort
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testclaim
  labels:
    lkey: lvalue
spec:
  storageClassName: testclass 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: volume-capacity